<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251127061657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE apparence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre_affichage INT NOT NULL, titre VARCHAR(255) NOT NULL, images JSON DEFAULT NULL, description VARCHAR(255) NOT NULL, personnage_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_902AE30A5E315342 ON apparence (personnage_id)');
        $this->addSql('CREATE TABLE commentaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, personnage_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F068BC5E315342 ON commentaire (personnage_id)');
        $this->addSql('CREATE TABLE histoire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre_affichage INT NOT NULL, titre VARCHAR(255) NOT NULL, categorie VARCHAR(255) DEFAULT NULL, description VARCHAR(255) NOT NULL, personnage_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD74CD685E315342 ON histoire (personnage_id)');
        $this->addSql('CREATE TABLE mod_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, nb_sig INT NOT NULL, sanctions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE moderateur (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE personnage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, is_public BOOLEAN NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AEA486DFB88E14F ON personnage (utilisateur_id)');
        $this->addSql('CREATE TABLE personnage_personnage (personnage_source INT NOT NULL, personnage_target INT NOT NULL, PRIMARY KEY (personnage_source, personnage_target))');
        $this->addSql('CREATE INDEX IDX_F1BF9378992CF5CD ON personnage_personnage (personnage_source)');
        $this->addSql('CREATE INDEX IDX_F1BF937880C9A542 ON personnage_personnage (personnage_target)');
        $this->addSql('CREATE TABLE signalement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4B55114FB88E14F ON signalement (utilisateur_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, status_id INT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B36BF700BD ON utilisateur (status_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON utilisateur (email)');
        $this->addSql('CREATE TABLE utilisateur_utilisateur (utilisateur_source INT NOT NULL, utilisateur_target INT NOT NULL, PRIMARY KEY (utilisateur_source, utilisateur_target))');
        $this->addSql('CREATE INDEX IDX_E9FA6E203E2745F8 ON utilisateur_utilisateur (utilisateur_source)');
        $this->addSql('CREATE INDEX IDX_E9FA6E2027C21577 ON utilisateur_utilisateur (utilisateur_target)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76BF396750 FOREIGN KEY (id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE apparence ADD CONSTRAINT FK_902AE30A5E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC5E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE histoire ADD CONSTRAINT FK_FD74CD685E315342 FOREIGN KEY (personnage_id) REFERENCES personnage (id)');
        $this->addSql('ALTER TABLE moderateur ADD CONSTRAINT FK_6DDC3554BF396750 FOREIGN KEY (id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnage ADD CONSTRAINT FK_6AEA486DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF9378992CF5CD FOREIGN KEY (personnage_source) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnage_personnage ADD CONSTRAINT FK_F1BF937880C9A542 FOREIGN KEY (personnage_target) REFERENCES personnage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT FK_F4B55114FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B36BF700BD FOREIGN KEY (status_id) REFERENCES mod_status (id)');
        $this->addSql('ALTER TABLE utilisateur_utilisateur ADD CONSTRAINT FK_E9FA6E203E2745F8 FOREIGN KEY (utilisateur_source) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_utilisateur ADD CONSTRAINT FK_E9FA6E2027C21577 FOREIGN KEY (utilisateur_target) REFERENCES utilisateur (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76BF396750');
        $this->addSql('ALTER TABLE apparence DROP CONSTRAINT FK_902AE30A5E315342');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC5E315342');
        $this->addSql('ALTER TABLE histoire DROP CONSTRAINT FK_FD74CD685E315342');
        $this->addSql('ALTER TABLE moderateur DROP CONSTRAINT FK_6DDC3554BF396750');
        $this->addSql('ALTER TABLE personnage DROP CONSTRAINT FK_6AEA486DFB88E14F');
        $this->addSql('ALTER TABLE personnage_personnage DROP CONSTRAINT FK_F1BF9378992CF5CD');
        $this->addSql('ALTER TABLE personnage_personnage DROP CONSTRAINT FK_F1BF937880C9A542');
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT FK_F4B55114FB88E14F');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B36BF700BD');
        $this->addSql('ALTER TABLE utilisateur_utilisateur DROP CONSTRAINT FK_E9FA6E203E2745F8');
        $this->addSql('ALTER TABLE utilisateur_utilisateur DROP CONSTRAINT FK_E9FA6E2027C21577');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE apparence');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE histoire');
        $this->addSql('DROP TABLE mod_status');
        $this->addSql('DROP TABLE moderateur');
        $this->addSql('DROP TABLE personnage');
        $this->addSql('DROP TABLE personnage_personnage');
        $this->addSql('DROP TABLE signalement');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
